@host = http://localhost:3000


GET {{host}}/api/teachers?page=2
Authorization: 'si'

###
GET {{host}}/api/teachers/map

###
GET {{host}}/api/teachers/6

###
POST {{host}}/api/teachers
Content-Type: application/json

{
    "nombre": "Laura",
    "apellidos": "González Sánchez",
    "fecha_nacimiento": "1984-06-04 00:00:00",
    "foto": "https://i.pravatar.cc/500?u=josemaria.zapatabravo@peticiones.online",
    "direccion": "Calle Mayor 2",
    "ciudad": "Bilbao",
    "codigo_postal": 48001,
    "longitud": "-2.934614",
    "latitud": "43.262378",
    "telefono": "944123456",
    "cuota": "65",
    "experiencia": "Experta en enseñanza de idiomas",
    "usuario_id": 1016
}
###
PUT {{host}}/api/teachers/51
Content-Type: application/json

{
    "nombre": "Laura",
    "apellidos": "González Sánchez",
    "fecha_nacimiento": "1984-06-04 00:00:00",
    "foto": "https://i.pravatar.cc/500?u=josemaria.zapatabravo@peticiones.online",
    "direccion": "Calle Mayor 2",
    "ciudad": "Bilbao",
    "codigo_postal": 48002,
    "longitud": "-2.934614",
    "latitud": "43.262378",
    "telefono": "944123456",
    "cuota": "65",
    "experiencia": "Experta en enseñanza de idiomas"
}

###
DELETE {{host}}/api/teachers/51

###
POST   {{host}}/api/mail
Content-Type: application/json

{
  "destinatario": "danieldager@gmail.com",
  "asunto": "TFM",
  "cuerpo": "Este es un correo de teacherapp"
}

### API REGISTER
POST   {{host}}/api/users/register
Content-Type: application/json

{
  "username": "dc1",
  "email": "dc1@gmail.com",
  "password": "12345",
  "role" : "profesor"
}

### API LOGIN
POST   {{host}}/api/users/login
Content-Type: application/json

{
  "email": "dc1@gmail.com",
  "password": "12345"
}