@host = http://localhost:3000

GET {{host}}/api/teachers?page=4


###
GET {{host}}/api/teachers/201



###
POST {{host}}/api/teachers
Content-Type: application/json

{
    "first_name" : "daniel",
    "last_name" : "colmenares",
    "username" : "dcdager3",
    "email" : "dcdage5@example.com"
}
###
PUT {{host}}/api/teachers/201
Content-Type: application/json

{
    "first_name" : "daniel",
    "last_name" : "colmenares",
    "username" : "dcdager13",
    "email" : "dcdage50@example.com"
}

###
DELETE {{host}}/api/teachers/191

###
POST   {{host}}/api/mail
Content-Type: application/json

{
  "destinatario": "danieldager@gmail.com",
  "asunto": "TFM",
  "cuerpo": "Este es un correo de teacherapp"
}
